spring.application.name=devverse-backend

# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/devverse}
spring.datasource.username=${DB_USERNAME:test-username}
spring.datasource.password=${DB_PASSWORD:test-password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#debug=true

# JWT
jwt.secret-key=${JWT_SECRET:test-token}
jwt.access-ttl-sec=${JWT_ACCESS_TTL_SEC:3600}
jwt.refresh-ttl-sec=${JWT_REFRESH_TTL_SEC:259200}

jwt.refresh-token-cookie-name=${JWT_REFRESH_TOKEN_COOKIE_NAME:test-name}
jwt.cookie-secure=${JWT_COOKIE_SECURE:true}
jwt.cookie-http-only=${JWT_COOKIE_HTTP_ONLY:true}
jwt.cookie-same-site=${JWT_COOKIE_SAME_SITE:Lax}
jwt.cookie-domain=${JWT_COOKIE_DOMAIN:} 
#set this cookie domain name

# OAuth 2
# Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:test-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:test-client-secret}
spring.security.oauth2.client.registration.google.scope=email, profile, openid

# Github
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:test-client-id}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:test-client-secret}
spring.security.oauth2.client.registration.github.scope=user, email

app.auth.frontend.success-redirect-url=http://localhost:5173/auth/success

# Swagger/DOC
springdoc.swagger-ui.enabled=true